name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub (or your chosen registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker images for microservices
    - name: Build Docker images
      run: |
        docker build -t yourusername/book_catalog_image ./book_catalog
        docker build -t yourusername/inventory_management_image ./inventory_management

    # Push Docker images to Docker Hub (or your chosen registry)
    - name: Push Docker images
      run: |
        docker push yourusername/book_catalog_image
        docker push yourusername/inventory_management_image

  deploy_infrastructure:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Apply Terraform configuration to provision Azure resources
    - name: Terraform Apply
      run: terraform apply -auto-approve

  deploy_microservices:
    needs: deploy_infrastructure
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    # Deploy microservices to Azure Kubernetes Service (AKS)
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/book_catalog_deployment.yaml
        kubectl apply -f k8s/book_catalog_service.yaml
        kubectl apply -f k8s/inventory_management_deployment.yaml
        kubectl apply -f k8s/inventory_management_service.yaml
