name: Deploy to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub or Azure Container Registry (ACR)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker images for microservices
    - name: Build Docker images
      run: |
        docker-compose build

    # Push Docker images to Docker Hub or ACR
    - name: Push Docker images
      run: |
        docker-compose push

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Update to the version you need

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    # Apply Terraform scripts to provision AKS and other resources
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform

    # Configure kubectl with Azure credentials to access AKS
    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    # Deploy microservices to AKS
    - name: Deploy to AKS
      run: |
        kubectl apply -f ./kubernetes/book_catalog-deployment.yaml
        kubectl apply -f ./kubernetes/inventory_management-deployment.yaml
